display_vendor = comp.createComboSymbol("DisplayVendor", None, ["None", "AMP"])
#display_vendor = comp.createComboSymbol("DisplayVendor", None, ["None", "AMP", "MikroE"])
display_vendor.setLabel("Display Module Vendor")
display_vendor.setVisible(True)
display_vendor.setDependencies(onDisplayVendor, ["DisplayVendor"])

amp_displays = comp.createComboSymbol("AMPDisplay", None, ["E0352A01-AF", "AXE37A3AFS"])
amp_displays.setLabel("AMP Display Module")
amp_displays.setVisible(True)
amp_displays.setDependencies(onAmpDisplay, ["AMPDisplay"])
amp_displays.setVisible(False)

mikroe_displays = comp.createComboSymbol("MikroEDisplay", None, ["E-paper Bundle 2"])
mikroe_displays.setLabel("MikroE Display Module")
mikroe_displays.setVisible(False)

display_width = comp.createIntegerSymbol("EPDWidth", None)
display_width.setLabel("Width")
display_width.setReadOnly(True)
display_width.setDescription("Display width")
display_width.setDefaultValue(0)
display_width.setMin(0)

display_height = comp.createIntegerSymbol("EPDHeight", None)
display_height.setLabel("Height")
display_height.setReadOnly(True)
display_height.setDescription("Display width")
display_height.setDefaultValue(0)
display_height.setMin(0)
