# generate code files
projectPath = "config/" + Variables.get("__CONFIGURATION_NAME") + "/gfx/driver/epaper"

GFX_DRIVER_H = comp.createFileSymbol("GFX_DRIVER_H", None)
GFX_DRIVER_H.setSourcePath("../../templates/gfx_driver.h.ftl")
GFX_DRIVER_H.setDestPath("gfx/driver/")
GFX_DRIVER_H.setOutputName("gfx_driver.h")
GFX_DRIVER_H.setProjectPath(projectPath)
GFX_DRIVER_H.setType("HEADER")
GFX_DRIVER_H.setMarkup(True)

GFX_DRIVER_C = comp.createFileSymbol("GFX_DRIVER_C", None)
GFX_DRIVER_C.setSourcePath("../../templates/gfx_driver.c.ftl")
GFX_DRIVER_C.setDestPath("gfx/driver/")
GFX_DRIVER_C.setOutputName("gfx_driver.c")
GFX_DRIVER_C.setProjectPath(projectPath)
GFX_DRIVER_C.setType("SOURCE")
GFX_DRIVER_C.setMarkup(True)

GFX_EPD_CONTROLLER_C = comp.createFileSymbol("GFX_EPD_CONTROLLER_C", None)
GFX_EPD_CONTROLLER_C.setDestPath("gfx/driver/controller/epaper")
GFX_EPD_CONTROLLER_C.setSourcePath("templates/drv_gfx_EPD_controller.c")
GFX_EPD_CONTROLLER_C.setOutputName("drv_gfx_EPD_controller.c")
GFX_EPD_CONTROLLER_C.setProjectPath(projectPath)
GFX_EPD_CONTROLLER_C.setType("SOURCE")
GFX_EPD_CONTROLLER_C.setMarkup(True)

GFX_EPD_CONTROLLER_ASYNC_C = comp.createFileSymbol("GFX_EPD_CONTROLLER_ASYNC_C", None)
GFX_EPD_CONTROLLER_ASYNC_C.setDestPath("gfx/driver/controller/epaper")
GFX_EPD_CONTROLLER_ASYNC_C.setSourcePath("templates/drv_gfx_EPD_controller_async.c.ftl")
GFX_EPD_CONTROLLER_ASYNC_C.setOutputName("drv_gfx_EPD_controller.c")
GFX_EPD_CONTROLLER_ASYNC_C.setProjectPath(projectPath)
GFX_EPD_CONTROLLER_ASYNC_C.setType("SOURCE")
GFX_EPD_CONTROLLER_ASYNC_C.setMarkup(True)
GFX_EPD_CONTROLLER_ASYNC_C.setEnabled(False)

GFX_EPD_CONTROLLER_H = comp.createFileSymbol("GFX_EPD_CONTROLLER_H", None)
GFX_EPD_CONTROLLER_H.setDestPath("gfx/driver/controller/epaper/")
GFX_EPD_CONTROLLER_H.setSourcePath("templates/drv_gfx_EPD_controller.h")
GFX_EPD_CONTROLLER_H.setOutputName("drv_gfx_EPD_controller.h")
GFX_EPD_CONTROLLER_H.setProjectPath(projectPath)
GFX_EPD_CONTROLLER_H.setType("HEADER")
GFX_EPD_CONTROLLER_H.setMarkup(False)

GFX_EPD_IOCTL_H = comp.createFileSymbol("GFX_EPD_IOCTL_H", None)
GFX_EPD_IOCTL_H.setDestPath("gfx/driver/controller/epaper/")
GFX_EPD_IOCTL_H.setSourcePath("templates/drv_gfx_EPD_ioctl.h")
GFX_EPD_IOCTL_H.setOutputName("drv_gfx_EPD_ioctl.h")
GFX_EPD_IOCTL_H.setProjectPath(projectPath)
GFX_EPD_IOCTL_H.setType("HEADER")
GFX_EPD_IOCTL_H.setMarkup(False)

GFX_EPD_CONTROLLER_LOCAL_H = comp.createFileSymbol("GFX_EPD_CONTROLLER_LOCAL_H", None)
GFX_EPD_CONTROLLER_LOCAL_H.setDestPath("gfx/driver/controller/epaper/")
GFX_EPD_CONTROLLER_LOCAL_H.setSourcePath("templates/drv_gfx_EPD_controller_local.h")
GFX_EPD_CONTROLLER_LOCAL_H.setOutputName("drv_gfx_EPD_controller_local.h")
GFX_EPD_CONTROLLER_LOCAL_H.setProjectPath(projectPath)
GFX_EPD_CONTROLLER_LOCAL_H.setType("HEADER")
GFX_EPD_CONTROLLER_LOCAL_H.setMarkup(False)

GFX_EPD_CONFIG_H = comp.createFileSymbol("GFX_EPD_CONFIG_H", None)
GFX_EPD_CONFIG_H.setDestPath("gfx/driver/controller/epaper/")
GFX_EPD_CONFIG_H.setSourcePath("templates/drv_gfx_EPD_config.h.ftl")
GFX_EPD_CONFIG_H.setOutputName("drv_gfx_EPD_config.h")
GFX_EPD_CONFIG_H.setProjectPath(projectPath)
GFX_EPD_CONFIG_H.setType("HEADER")
GFX_EPD_CONFIG_H.setMarkup(True)

# UltraChip UC8253 files
GFX_EPD_UC8253_C = comp.createFileSymbol("GFX_EPD_UC8253_C", None)
GFX_EPD_UC8253_C.setDestPath("gfx/driver/controller/epaper/UltraChip/UC8253/")
GFX_EPD_UC8253_C.setSourcePath("templates/UltraChip/UC8253/drv_gfx_EPD_AMP_UC8253.c")
GFX_EPD_UC8253_C.setOutputName("drv_gfx_EPD_AMP_UC8253.c")
GFX_EPD_UC8253_C.setProjectPath(projectPath)
GFX_EPD_UC8253_C.setType("SOURCE")
GFX_EPD_UC8253_C.setMarkup(False)
GFX_EPD_UC8253_C.setEnabled(False)

GFX_EPD_UC8253_H = comp.createFileSymbol("GFX_EPD_UC8253_H", None)
GFX_EPD_UC8253_H.setDestPath("gfx/driver/controller/epaper/UltraChip/UC8253/")
GFX_EPD_UC8253_H.setSourcePath("templates/UltraChip/UC8253/drv_gfx_EPD_AMP_UC8253.h")
GFX_EPD_UC8253_H.setOutputName("drv_gfx_EPD_AMP_UC8253.h")
GFX_EPD_UC8253_H.setProjectPath(projectPath)
GFX_EPD_UC8253_H.setType("HEADER")
GFX_EPD_UC8253_H.setMarkup(False)
GFX_EPD_UC8253_H.setEnabled(False)

GFX_EPD_UC8253_LOCAL_H = comp.createFileSymbol("GFX_EPD_UC8253_LOCAL_H", None)
GFX_EPD_UC8253_LOCAL_H.setDestPath("gfx/driver/controller/epaper/UltraChip/UC8253/")
GFX_EPD_UC8253_LOCAL_H.setSourcePath("templates/UltraChip/UC8253/drv_gfx_EPD_AMP_UC8253_local.h")
GFX_EPD_UC8253_LOCAL_H.setOutputName("drv_gfx_EPD_AMP_UC8253_local.h")
GFX_EPD_UC8253_LOCAL_H.setProjectPath(projectPath)
GFX_EPD_UC8253_LOCAL_H.setType("HEADER")
GFX_EPD_UC8253_LOCAL_H.setMarkup(False)
GFX_EPD_UC8253_LOCAL_H.setEnabled(False)

GFX_EPD_UC8253_LUT_C = comp.createFileSymbol("GFX_EPD_UC8253_LUT_C", None)
GFX_EPD_UC8253_LUT_C.setDestPath("gfx/driver/controller/epaper/UltraChip/UC8253/")
GFX_EPD_UC8253_LUT_C.setSourcePath("templates/UltraChip/UC8253/drv_gfx_EPD_AMP_UC8253_LUT.c")
GFX_EPD_UC8253_LUT_C.setOutputName("drv_gfx_EPD_AMP_UC8253_LUT.c")
GFX_EPD_UC8253_LUT_C.setProjectPath(projectPath)
GFX_EPD_UC8253_LUT_C.setType("SOURCE")
GFX_EPD_UC8253_LUT_C.setMarkup(False)
GFX_EPD_UC8253_LUT_C.setEnabled(False)

GFX_EPD_UC8253_LUT_H = comp.createFileSymbol("GFX_EPD_UC8253_LUT_H", None)
GFX_EPD_UC8253_LUT_H.setDestPath("gfx/driver/controller/epaper/UltraChip/UC8253/")
GFX_EPD_UC8253_LUT_H.setSourcePath("templates/UltraChip/UC8253/drv_gfx_EPD_AMP_UC8253_LUT.h")
GFX_EPD_UC8253_LUT_H.setOutputName("drv_gfx_EPD_AMP_UC8253_LUT.h")
GFX_EPD_UC8253_LUT_H.setProjectPath(projectPath)
GFX_EPD_UC8253_LUT_H.setType("HEADER")
GFX_EPD_UC8253_LUT_H.setMarkup(False)
GFX_EPD_UC8253_LUT_H.setEnabled(False)

# Waveshare MIKROE 2.13" files
GFX_EPD_MIKROE_2N13_C = comp.createFileSymbol("GFX_EPD_MIKROE_2N13_C", None)
GFX_EPD_MIKROE_2N13_C.setDestPath("gfx/driver/controller/epaper/Waveshare/MIKROE_2n13/")
GFX_EPD_MIKROE_2N13_C.setSourcePath("templates/Waveshare/MIKROE_2n13/drv_gfx_EPD_MIKROE_2n13.c")
GFX_EPD_MIKROE_2N13_C.setOutputName("drv_gfx_EPD_MIKROE_2n13.c")
GFX_EPD_MIKROE_2N13_C.setProjectPath(projectPath)
GFX_EPD_MIKROE_2N13_C.setType("SOURCE")
GFX_EPD_MIKROE_2N13_C.setMarkup(False)
GFX_EPD_MIKROE_2N13_C.setEnabled(False)

GFX_EPD_MIKROE_2N13_H = comp.createFileSymbol("GFX_EPD_MIKROE_2N13_H", None)
GFX_EPD_MIKROE_2N13_H.setDestPath("gfx/driver/controller/epaper/Waveshare/MIKROE_2n13/")
GFX_EPD_MIKROE_2N13_H.setSourcePath("templates/Waveshare/MIKROE_2n13/drv_gfx_EPD_MIKROE_2n13.h")
GFX_EPD_MIKROE_2N13_H.setOutputName("drv_gfx_EPD_MIKROE_2n13.h")
GFX_EPD_MIKROE_2N13_H.setProjectPath(projectPath)
GFX_EPD_MIKROE_2N13_H.setType("HEADER")
GFX_EPD_MIKROE_2N13_H.setMarkup(False)
GFX_EPD_MIKROE_2N13_H.setEnabled(False)

GFX_EPD_MIKROE_2N13_LOCAL_H = comp.createFileSymbol("GFX_EPD_MIKROE_2N13_LOCAL_H", None)
GFX_EPD_MIKROE_2N13_LOCAL_H.setDestPath("gfx/driver/controller/epaper/Waveshare/MIKROE_2n13/")
GFX_EPD_MIKROE_2N13_LOCAL_H.setSourcePath("templates/Waveshare/MIKROE_2n13/drv_gfx_EPD_MIKROE_2n13_local.h")
GFX_EPD_MIKROE_2N13_LOCAL_H.setOutputName("drv_gfx_EPD_MIKROE_2n13_local.h")
GFX_EPD_MIKROE_2N13_LOCAL_H.setProjectPath(projectPath)
GFX_EPD_MIKROE_2N13_LOCAL_H.setType("HEADER")
GFX_EPD_MIKROE_2N13_LOCAL_H.setMarkup(False)
GFX_EPD_MIKROE_2N13_LOCAL_H.setEnabled(False)

GFX_EPD_MIKROE_2N13_LUT_C = comp.createFileSymbol("GFX_EPD_MIKROE_2N13_LUT_C", None)
GFX_EPD_MIKROE_2N13_LUT_C.setDestPath("gfx/driver/controller/epaper/Waveshare/MIKROE_2n13/")
GFX_EPD_MIKROE_2N13_LUT_C.setSourcePath("templates/Waveshare/MIKROE_2n13/drv_gfx_EPD_MIKROE_2n13_lut.c")
GFX_EPD_MIKROE_2N13_LUT_C.setOutputName("drv_gfx_EPD_MIKROE_2n13_lut.c")
GFX_EPD_MIKROE_2N13_LUT_C.setProjectPath(projectPath)
GFX_EPD_MIKROE_2N13_LUT_C.setType("SOURCE")
GFX_EPD_MIKROE_2N13_LUT_C.setMarkup(False)
GFX_EPD_MIKROE_2N13_LUT_C.setEnabled(False)

GFX_EPD_MIKROE_2N13_LUT_H = comp.createFileSymbol("GFX_EPD_MIKROE_2N13_LUT_H", None)
GFX_EPD_MIKROE_2N13_LUT_H.setDestPath("gfx/driver/controller/epaper/Waveshare/MIKROE_2n13/")
GFX_EPD_MIKROE_2N13_LUT_H.setSourcePath("templates/Waveshare/MIKROE_2n13/drv_gfx_EPD_MIKROE_2n13_lut.h")
GFX_EPD_MIKROE_2N13_LUT_H.setOutputName("drv_gfx_EPD_MIKROE_2n13_lut.h")
GFX_EPD_MIKROE_2N13_LUT_H.setProjectPath(projectPath)
GFX_EPD_MIKROE_2N13_LUT_H.setType("HEADER")
GFX_EPD_MIKROE_2N13_LUT_H.setMarkup(False)
GFX_EPD_MIKROE_2N13_LUT_H.setEnabled(False)

GFX_EPD_MIKROE_2N13_IMAGE_H = comp.createFileSymbol("GFX_EPD_MIKROE_2N13_IMAGE_H", None)
GFX_EPD_MIKROE_2N13_IMAGE_H.setDestPath("gfx/driver/controller/epaper/Waveshare/MIKROE_2n13/")
GFX_EPD_MIKROE_2N13_IMAGE_H.setSourcePath("templates/Waveshare/MIKROE_2n13/eink213inch_image.h")
GFX_EPD_MIKROE_2N13_IMAGE_H.setOutputName("eink213inch_image.h")
GFX_EPD_MIKROE_2N13_IMAGE_H.setProjectPath(projectPath)
GFX_EPD_MIKROE_2N13_IMAGE_H.setType("HEADER")
GFX_EPD_MIKROE_2N13_IMAGE_H.setMarkup(False)
GFX_EPD_MIKROE_2N13_IMAGE_H.setEnabled(False)